// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUIGNIVBiMdOcasTYFXZ5JZkKijEiJUIQ',
    appId: '1:661069302832:web:309042e97beb0fb4f6f1f5',
    messagingSenderId: '661069302832',
    projectId: 'farmermarketplace-5577c',
    authDomain: 'farmermarketplace-5577c.firebaseapp.com',
    storageBucket: 'farmermarketplace-5577c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjxIHjKXf16JA_p9wd8ZDTOhAF7z93j2w',
    appId: '1:661069302832:android:25beac5d66356093f6f1f5',
    messagingSenderId: '661069302832',
    projectId: 'farmermarketplace-5577c',
    storageBucket: 'farmermarketplace-5577c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFGOZbAGeszMK4Le0BB4tlQvX1UclTpYs',
    appId: '1:661069302832:ios:2cad862a5179b5e4f6f1f5',
    messagingSenderId: '661069302832',
    projectId: 'farmermarketplace-5577c',
    storageBucket: 'farmermarketplace-5577c.firebasestorage.app',
    iosBundleId: 'com.example.farmermarketplace',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFGOZbAGeszMK4Le0BB4tlQvX1UclTpYs',
    appId: '1:661069302832:ios:2cad862a5179b5e4f6f1f5',
    messagingSenderId: '661069302832',
    projectId: 'farmermarketplace-5577c',
    storageBucket: 'farmermarketplace-5577c.firebasestorage.app',
    iosBundleId: 'com.example.farmermarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUIGNIVBiMdOcasTYFXZ5JZkKijEiJUIQ',
    appId: '1:661069302832:web:e750239eacd96f2df6f1f5',
    messagingSenderId: '661069302832',
    projectId: 'farmermarketplace-5577c',
    authDomain: 'farmermarketplace-5577c.firebaseapp.com',
    storageBucket: 'farmermarketplace-5577c.firebasestorage.app',
  );
}
